#!/usr/bin/env python3
"""results/summary.md from results/run.json.   python scripts/summarize.py [results]"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "results")
out = []


def load(name):
    p = os.path.join(R, name)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def P(s=""):
    out.append(s)


def table(cols, rows):
    P("| " + " | ".join(cols) + " |"); P("|" + "---|" * len(cols))
    for r in rows:
        P("| " + " | ".join(str(c) for c in r) + " |")
    P()


def pct(x, d=2):
    return "-" if x is None else f"{100 * x:.{d}f} %"


def bp(x):
    return "-" if x is None else f"{1e4 * x:.0f} bp"


run = load("run.json")
if not run:
    raise SystemExit("no results/run.json")

P("# Results summary\n")
P("Generated by scripts/summarize.py from results/run.json.\n")
h = run.get("headline"); st = run["strategies"]
if h:
    name = h["strategy"]; s = st[name]; bn = s["books"]["naive"]; ba = s["books"]["borrow_aware"]; bf = s["books"]["frictionless"]; br = s["books"]["risk_only"]
    P(f"## The one number\n")
    P(f"On the {name} book (${h['nav0'] / 1e6:.0f}m NAV, {h['gross_exposure']}, {s['rebalances']} rebalances from {s['first']} to {s['last']}, equal-weighted deciles of {run['universe']} names), **borrow fees and recalls cost {pct(bn['ann_fees'] + bn['ann_recall_impact'])} of NAV a year** ({pct(bn['ann_fees'])} in fees at a weighted fee of {pct(bn['fee_wavg_short'])} on the short leg, {pct(bn['ann_recall_impact'])} in forced covers and re-entries: {bn['recalls_per_month']:.1f} recalls a month on about {round(s['optimiser']['risk_only']['avg_n_short'])} shorts). "
      f"{pct(bn['locate_failure_rate'], 1)} of the shorts requested at a rebalance could not be located and the book was missing an intended short on {pct(bn['missing_short_days_share'], 1)} of position-days; the price return the book missed by not holding those names came to {pct(bn['ann_opportunity_short'])} a year (negative means the unavailable names went the wrong way for a short, so missing them helped). "
      f"The borrow-aware optimiser, allowed to substitute from the next decile, brings fees to {pct(ba['ann_fees'])} and recalls to {pct(ba['ann_recall_impact'])} ({ba['recalls_per_month']:.1f} a month, locate failures {pct(ba['locate_failure_rate'], 1)}): **a recovery of {pct(h['certain_recovery_vs_risk_only'])} of NAV a year in fees and recalls against the same optimiser without the borrow term** ({pct(h['drag_reduction_vs_risk_only'])} all-in once the missed-shorts term is included), for a net return of {pct(ba['ann_return'])} against {pct(bn['ann_return'])} naive ({pct(h['net_gain_vs_naive'])}). Without any lending friction the same book returns {pct(bf['ann_return'])}.\n")
    P(f"## {name}: the four books\n")
    dt = s["drag_table"]
    table(["book", "gross price P&L", "long leg", "short leg", "shadow short leg", "missed shorts", "borrow fees", "recalls", "rebalance impact", "rebate + cash", "net return (log)", "vol", "max DD", "fee on short leg", "locate failures", "recalls / 100 position-months", "missing short-days"],
          [[k, pct(v["gross_price_pnl"]), pct(v["pnl_long"]), pct(v["pnl_short"]), pct(v["shadow_pnl_short"]), pct(v["opportunity_cost"]), pct(v["borrow_fees"]), pct(v["recall_impact"]), pct(v["rebalance_impact"]), pct(v["rebate"] + v["cash_financing"]), pct(v["net_return"]), pct(s["books"][k]["ann_vol"], 0), pct(s["books"][k]["max_drawdown"], 0), pct(v["fee_wavg"]), pct(v["locate_failure_rate"], 1), f"{v['recalls_per_100_position_months']:.1f}", pct(v["missing_short_days_share"], 1)] for k, v in dt.items()])
    P("All flows are annualised as a share of the running NAV; the net return is the annualised log return of the NAV. The shadow short leg holds every intended short without locates or recalls, so 'missed shorts' is the price return the real short leg did not get (the shadow leg's return less the real short leg's).\n")
    o = s["optimiser"]
    P(f"Optimiser (lambda = {s['lam']}, alpha spread {pct(s['alpha_spread_monthly'], 1)} a month, tracking-variance penalty against the naive book): the risk-only book has an active share of {pct(o['risk_only']['avg_active_share'], 1)} against the naive deciles and the borrow-aware book {pct(o['borrow_aware']['avg_active_share'], 1)}; {pct(o['borrow_aware']['avg_short_in_bottom_decile'], 0)} of the borrow-aware short leg stays in the bottom decile; the expected monthly borrow cost of the short leg falls from {bp(o['borrow_aware']['avg_expected_borrow_cost_naive'])} to {bp(o['borrow_aware']['avg_expected_borrow_cost_monthly'])} of NAV.\n")

P("## The three books\n")
rows = []
for n, s in st.items():
    if "drag_table" not in s:
        continue
    dn, da, dr = s["drag_table"]["naive"], s["drag_table"]["borrow_aware"], s["drag_table"]["risk_only"]
    rows.append([n, s["signal"].split(":")[0], pct(dn["fee_wavg"]), pct(da["fee_wavg"]), pct(dn["locate_failure_rate"], 1), pct(da["locate_failure_rate"], 1), f"{dn['recalls_per_100_position_months']:.1f} / {da['recalls_per_100_position_months']:.1f}", pct(dn["borrow_fees"] + dn["recall_impact"]), pct(da["borrow_fees"] + da["recall_impact"]), pct(dn["opportunity_cost"]), pct(da["opportunity_cost"]), pct(dn["net_return"]), pct(dr["net_return"]), pct(da["net_return"]), pct(s["books"]["frictionless"]["ann_return"])])
table(["book", "signal", "fee, naive", "fee, aware", "locate fail, naive", "aware", "recalls / 100 position-months naive / aware", "fees + recalls, naive", "aware", "missed shorts, naive", "aware", "net, naive", "net, risk-only", "net, borrow-aware", "net, no frictions"], rows)

fc = run["fee_checks"]; d = fc["distribution_last_day"]
P("## The borrow model\n")
P(f"Fee source: {fc['fee_source']} (no Interactive Brokers snapshots were reachable; see the data section). On {d['date']}, {d['n']} names: {pct(d['share_gc_below_1pct'], 0)} general collateral (fee under 1 %; the published figure is 85-92 %), {pct(d['share_special_above_5pct'], 1)} special (over 5 %), mean fee {pct(d['mean_fee'])}, median {pct(d['quantiles']['p50'])}, p90 {pct(d['quantiles']['p90'])}, p99 {pct(d['quantiles']['p99'])}; {d['on_threshold']} names on a Reg SHO threshold list, {d['utilisation_above_0_8']} with utilisation above 80 % of modelled lendable supply, the utilisation floor binding for {d.get('fee_floor_binds', 0)}. "
  f"Names on a threshold list carry a mean fee of {pct(fc['threshold_names']['mean_fee_on_threshold'])} against {pct(fc['threshold_names']['mean_fee_off_threshold'])} off it.\n")
fwd = fc["forward_return_by_fee_bucket"]
if fwd:
    table(["fee bucket at month end", "next-month return (equal weight)", "t", "months", "avg names"], [[k, pct(v["mean_monthly_return"]), f"{v['t_stat']:.1f}" if v.get("t_stat") is not None else "-", v["months"], f"{v['avg_names']:.0f}"] for k, v in fwd.items() if k != "gc_minus_special"])
    if "gc_minus_special" in fwd:
        g = fwd["gc_minus_special"]; P(f"General collateral minus special: {pct(g['mean_monthly'])} a month (t = {g['t_stat']:.1f}, {g['months']} months). The literature's sign is positive (expensive-to-short names underperform); it is a check on the ordering, not a strategy.\n")

if "sensitivity" in run:
    P("## Sensitivity\n")
    table(["fee scale", "hazard scale", "fees + recalls, naive", "borrow-aware", "all-in drag, naive", "borrow-aware", "recalls / month naive", "aware", "net naive", "net aware", "gain"], [[g["fee_scale"], g["hazard_scale"], pct(g["certain_naive"]), pct(g["certain_aware"]), pct(g["drag_naive"]), pct(g["drag_borrow_aware"]), f"{g['recalls_naive']:.1f}", f"{g['recalls_aware']:.1f}", pct(g["net_naive"]), pct(g["net_borrow_aware"]), pct(g["gain"])] for g in run["sensitivity"]["grid"]])
    table(["seed", "fees + recalls, naive", "borrow-aware", "missed shorts, naive", "locate failures, naive", "recalls / month", "net naive", "net aware"], [[g["seed"], pct(g["certain_naive"]), pct(g["certain_aware"]), pct(g["opportunity_naive"]), pct(g["locate_failure_naive"], 1), f"{g['recalls_naive']:.1f}", pct(g["net_naive"]), pct(g["net_borrow_aware"])] for g in run["sensitivity"]["seeds"]])
if run.get("alpha_sensitivity"):
    table(["alpha spread / month", "lambda", "shorts held, aware", "fees + recalls, naive", "borrow-aware", "fees aware", "locate fail aware", "net naive", "net aware"], [[pct(a["alpha_spread_monthly"], 1), a["lam"], f"{a['avg_n_short']:.0f}", pct(a["certain_naive"]), pct(a["certain_borrow_aware"]), pct(a["fees_borrow_aware"]), pct(a["locate_failure_borrow_aware"], 1), pct(a["net_return_naive"]), pct(a["net_return_borrow_aware"])] for a in run["alpha_sensitivity"]])

f = run.get("financing")
if f:
    P("## Financing and the prime-broker reconciliation\n")
    a = f["annualised_over_nav"]; m = f["margin_last_day"]
    P(f"On the naive {run['headline']['strategy']} book the short rebate earns {pct(a.get('short_rebate'))} of NAV a year (EFFR on the short proceeds, ACT/360), borrow fees cost {pct(-a.get('borrow_fee', 0))} and the cash balance {pct(a.get('cash_interest'))}: net financing {pct(f['net_financing_ann'])} a year over {f['days']} days and {f['lines']:,} accrual lines. "
      f"On the last day the book is ${m['gross'] / 1e6:,.0f}m gross ({m['leverage']:.2f}x NAV): Regulation T initial margin ${m['regt_initial'] / 1e6:,.0f}m (excess ${m['excess_regt_initial'] / 1e6:,.0f}m), maintenance ${m['regt_maintenance'] / 1e6:,.0f}m, portfolio margin ${m['portfolio_margin'] / 1e6:,.0f}m (excess ${m['excess_pm'] / 1e6:,.0f}m). Reg T maintenance was breached on {f['margin_breaches_regt_maintenance']} days and portfolio margin on {f['margin_breaches_pm']} days; the minimum excess equity was {pct(f['min_excess_regt_over_nav'], 0)} of NAV under Reg T and {pct(f['min_excess_pm_over_nav'], 0)} under portfolio margin.\n")
    rc = f["reconciliation"]
    P(f"The simulated PB statement has {rc['pb_lines']:,} lines against {rc['book_lines']:,} in the book ({rc['keys']:,} date-symbol-kind keys). The reconciliation raised {rc['breaks']:,} breaks ({rc['material_breaks']:,} above the ${rc['tolerance_usd']:.2f} tolerance) and {rc['false_positives']} on keys with nothing seeded; {pct(rc['overall_detection'], 1)} of the seeded discrepancies were found and classified as the right type.\n")
    table(["seeded discrepancy", "expected break type", "seeded", "found as expected", "found as another type"], [[k, v["expected_type"], v["seeded"], v["detected_as_expected"], v["detected_other_type"]] for k, v in rc["seeded"].items()])
    table(["break type", "keys", "net $ (PB minus book)"], [[k, v, f"{rc['breaks_usd_by_type'].get(k, 0):,.0f}"] for k, v in rc["breaks_by_type"].items()])

bm = run["borrow_model"]; s_ = run["store"]
P("## Data\n")
P(f"As of {run['as_of']}: {run['universe']} names, {bm.get('rows', 0):,} name-days in the borrow table from {bm.get('from', '')}; store: {s_.get('prices', 0):,} price bars, {s_.get('short_interest_rows', 0):,} FINRA short-interest rows over {s_.get('short_interest_dates', 0)} settlement dates, {s_.get('threshold_rows', 0):,} threshold-list rows over {s_.get('threshold_days', 0)} days, {s_.get('ftd_rows', 0):,} fails-to-deliver rows, {s_.get('symbol_changes', 0)} ticker changes in the point-in-time map, {s_.get('ib_rows', 0)} IB shortable rows, {s_.get('effr_days', 0)} EFFR days. Runtime {run['seconds'] / 60:.0f} minutes.\n")

with open(os.path.join(R, "summary.md"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(out))
print("wrote", os.path.join(R, "summary.md"))
